services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  MichielRoos\WizardCrpagetree\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'

  MichielRoos\WizardCrpagetree\EventListener\BackendControllerEvent:
    public: true
    tags:
      - name: event.listener
        identifier: 'add-js-event'
        event: \TYPO3\CMS\Backend\Controller\Event\AfterBackendPageRenderEvent
